[package]
name = "saddle-rendering-sprite-effects-example-dissolve"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { workspace = true }
saddle-rendering-sprite-effects = { workspace = true }
saddle-rendering-sprite-effects-example-common = { path = "../common" }
saddle-pane = { git = "https://github.com/julien-blanchon/saddle-pane" }

[lints]
workspace = true
